#!/bin/sh
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# enable only git 
#zstyle ':vcs_info:*' enable git 
# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats ' %F{#8c7e6a}%b |'

setopt PROMPT_SUBST
PROMPT='${vcs_info_msg_0_} %F{#8c7e6a}%~ %B%(0?.%F{5}.%F{red})$ %{$reset_color%}'
